basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a simple API to reconstruct flight itineraries from given tickets.
  title: Flight Itinerary API
  version: "1.0"
paths:
  /itinerary:
    post:
      consumes:
      - application/json
      description: Reconstruct the complete flight itinerary from given tickets
      parameters:
      - description: Array of ticket pairs
        in: body
        name: tickets
        required: true
        schema:
          items:
            items:
              items:
                type: string
              type: array
            type: array
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: Complete itinerary
          schema:
            items:
              type: string
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to construct itinerary
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reconstruct flight itinerary
swagger: "2.0"
